### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by gushedaoren** [TencentBlueKing/bk-itsm#1017]
[root@bk-dev-24-47 pc]# npm run dev

> itsm@1.0.0 dev
> cross-env webpack-dev-server --progress --config ./build/webpack.dev.conf.js

/data/projects/atlas/src/itsm/frontend/pc/node_modules/webpack-cli/bin/utils/prompt-command.js:46
	return func(...args);
	       ^

TypeError: Class constructor ServeCommand cannot be invoked without 'new'
    at runWhenInstalled (/data/projects/atlas/src/itsm/frontend/pc/node_modules/webpack-cli/bin/utils/prompt-command.js:46:9)
    at promptForInstallation (/data/projects/atlas/src/itsm/frontend/pc/node_modules/webpack-cli/bin/utils/prompt-command.js:140:10)
    at /data/projects/atlas/src/itsm/frontend/pc/node_modules/webpack-cli/bin/cli.js:32:43
    at Object.<anonymous> (/data/projects/atlas/src/itsm/frontend/pc/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)

**Comment by houming818** [comment]
https://www.grepcode.cn/2023/11/blueking_itsm_01/

解决了。
