### ISSUE TITLE
itsm2.5.8升级2.6.0部署失败问题

### ISSUE THREAD

**Issue by qifeng998130** [TencentBlueKing/bk-itsm#1030]
![image](https://user-images.githubusercontent.com/12607253/208601042-8433bc8e-cd88-4eb4-a77f-e0005d0d042c.png)

execute operation [upsert_action] id=knowledge_manage success!
execute operation [upsert_action] id=operational_data_view success!
execute operation [upsert_resource_type] id=field success!
_call_iam_api fail. method: http_put path: /api/v1/model/systems/bk_itsm/actions/ticket_manage error: conflict:action name[工单管理] already exists
execute operation [upsert_action] conflict:action name[工单管理] already exists fail, error message: id=ticket_manage
Traceback (most recent call last):
  File "manage.py", line 43, in <module>
  File "/cache/.bk/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/cache/.bk/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/cache/.bk/env/lib/python3.6/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/cache/.bk/env/lib/python3.6/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/cache/.bk/env/lib/python3.6/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/cache/.bk/env/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 246, in handle
    fake_initial=fake_initial,
  File "/cache/.bk/env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/cache/.bk/env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/cache/.bk/env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/cache/.bk/env/lib/python3.6/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/cache/.bk/env/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/data/app/code/iam/contrib/iam_migration/migrations/0007_update.py", line 16, in forward_func
  File "/data/app/code/iam/contrib/iam_migration/migrator.py", line 65, in migrate
iam.contrib.iam_migration.exceptions.MigrationFailError: iam migrate fail
------FAILURE: Migrate Database------
[10.0.2.171]20221220-135124 105   [JOB FAILURE]

@zanyzhao @irwinsun @breezelxp @hanshuaikang @luofann

**Comment by hanshuaikang** [comment]
升级到2.5.9 再升级 2.6.0 试下呢？
