### ISSUE TITLE
多个api节点并行执行时出现死锁，导致流程假死

### ISSUE THREAD

**Issue by shanwei0619** [TencentBlueKing/bk-itsm#1350]
**现象：**五个api执行步骤用并行网关支持同时触发时，下面报错必现，导致的现象就是api执行阶段会一直在转圈，无法进行下一步，假死现象；
**报错信息：**itsm报错信息：

[2024-06-14 16:57:41,987: ERROR/MainProcess] Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/app/.heroku/python/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/app/.heroku/python/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/app/.heroku/python/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

The above exception was the direct cause of the following exception:

[2024-06-14 16:57:41,987: ERROR/MainProcess] (1213, 'Deadlock found when trying to get lock; try restarting transaction')
[2024-06-14 16:57:41,987: ERROR/MainProcess] Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/app/.heroku/python/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/app/.heroku/python/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/app/.heroku/python/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

The above exception was the direct cause of the following exception:

**Comment by benero** [comment]
已修复，可部署 2.7.0 版本处理，thx
