### ISSUE TITLE
NetworkUnreachableError: bk iam ping error

### ISSUE THREAD

**Issue by LiDan0420** [TencentBlueKing/bk-itsm#156]
`[root@localhost bk-itsm-master]# python manage.py migrate
init redis settings
autodiscover rpc: rpc.components
autodiscover trigger: action.components
System check identified some issues:

WARNINGS:
ticket.SignTask.is_passed: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
workflow.Workflow.is_task_needed: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
workflow.WorkflowVersion.is_task_needed: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
Operations to perform:
  Apply all migrations: account, admin, auth, auth_iam, component_framework, contenttypes, data_migration, django_celery_beat, django_celery_results, django_nyt, django_signal_valve, engine, iadmin, iam_migration, log, pipeline, postman, project, requests_tracker, role, service, sessions, sites, sla, sla_engine, task, thumbnail, ticket, ticket_status, trigger, variable_framework, weixin_core, workflow
Running migrations:
  Applying iam_migration.0001_initial...http request error! method: %s, url: %s, data: %s GET localhost/ping None
Traceback (most recent call last):
  File "manage.py", line 43, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 246, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/data/bk-itsm-master/iam/contrib/iam_migration/migrations/0001_initial.py", line 16, in forward_func
    migrator.migrate()
  File "/data/bk-itsm-master/iam/contrib/iam_migration/migrator.py", line 61, in migrate
    raise exceptions.NetworkUnreachableError("bk iam ping error")
iam.contrib.iam_migration.exceptions.NetworkUnreachableError: bk iam ping error`

请问下这个是什么问题 如何解决

**Comment by hanshuaikang** [comment]
如果只是本地测试，请设置 USE_IAM 环境变量 == false
