### ISSUE TITLE
部署itms错误

### ISSUE THREAD

**Issue by qifeng998130** [TencentBlueKing/bk-itsm#942]
![image](https://user-images.githubusercontent.com/12607253/190347869-32172bfe-01eb-424f-9e0a-4843be32afb6.png)
_call_iam_api fail. method: http_get path: /api/v1/model/systems/itsmnew/query error: not found:system(itsmnew) not exists

do api_query fail not found:system(itsmnew) not exists

_call_iam_api fail. method: http_post path: /api/v1/model/systems error: conflict:system name(流程服务) already exists

execute operation [upsert_system] conflict:system name(流程服务) already exists fail, error message: id=itsmnew

Traceback (most recent call last):

  File "manage.py", line 43, in 

    execute_from_command_line(sys.argv)

  File "/cache/.bk/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line

    utility.execute()

  File "/cache/.bk/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 413, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/cache/.bk/env/lib/python3.6/site-packages/django/core/management/base.py", line 354, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/cache/.bk/env/lib/python3.6/site-packages/django/core/management/base.py", line 398, in execute

    output = self.handle(*args, **options)

  File "/cache/.bk/env/lib/python3.6/site-packages/django/core/management/base.py", line 89, in wrapped

    res = handle_func(*args, **kwargs)

  File "/cache/.bk/env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate

    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)

  File "/cache/.bk/env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards

    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)

  File "/cache/.bk/env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 227, in apply_migration

    state = migration.apply(state, schema_editor)

  File "/cache/.bk/env/lib/python3.6/site-packages/django/db/migrations/migration.py", line 123, in apply

    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)

  File "/cache/.bk/env/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards

    self.code(from_state.apps, schema_editor)

  File "/data/app/code/iam/contrib/iam_migration/migrations/0001_initial.py", line 16, in forward_func

    migrator.migrate()

  File "/data/app/code/iam/contrib/iam_migration/migrator.py", line 65, in migrate

    raise exceptions.MigrationFailError("iam migrate fail")

iam.contrib.iam_migration.exceptions.MigrationFailError: iam migrate fail

20220915-141329 56   ------failure: migrate database------

[10.129.168.22]20220915-141331 105   [JOB FAILURE]

  File "/cache/.bk/env/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 246, in handle

    fake_initial=fake_initial,

求帮忙，那我大神遇到过这个问题，怎么解决的？
这问题没看懂：

_call_iam_api fail. method: http_get path: /api/v1/model/systems/itsmnew/query error: not found:system(itsmnew) not exists

do api_query fail not found:system(itsmnew) not exists

_call_iam_api fail. method: http_post path: /api/v1/model/systems error: conflict:system name(流程服务) already exists

execute operation [upsert_system] conflict:system name(流程服务) already exists fail, error message: id=itsmnew

**Comment by hanshuaikang** [comment]
私有化部署流程服务吗

**Comment by hanshuaikang** [comment]
请参考：https://github.com/TencentBlueKing/bk-itsm/blob/master/docs/install/source_code_deploy.md
