### ISSUE TITLE
itsm二次开发问题

### ISSUE THREAD

**Issue by qifeng998130** [TencentBlueKing/bk-itsm#975]
产品： 社区的版本
版本： 6.0.5
环境信息： centos7
![--0ed6417479a5b951ab56042739de8dc5](https://user-images.githubusercontent.com/12607253/195015569-6a5970a4-08de-4c1f-8665-8c0a0cff5341.png)
![--0192974c47b4367d50fdd6538fd3f678](https://user-images.githubusercontent.com/12607253/195015595-7fe374ce-2cc4-4ba6-be66-84f7ac67e0b1.png)
![--3f6521ae17f72fa49b6eb95618397765](https://user-images.githubusercontent.com/12607253/195015611-d74bb6a4-4fbd-410b-b884-834d30d8623e.png)
![--82233c2e8de5038e9ec4a8197badbc90](https://user-images.githubusercontent.com/12607253/195015629-b05326c9-618c-407f-bb10-e6376b3ded6d.png)

日志/data/bkce/paas_agent/apps/logs/itsmnew/celery.log
Traceback (most recent call last):
File "/data/app/code/manage.py", line 43, in <module>
execute_from_command_line(sys.argv)
File "/cache/.bk/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
utility.execute()
File "/cache/.bk/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
django.setup()
File "/cache/.bk/env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "/cache/.bk/env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
app_config.ready()
File "/data/app/code/itsm/workflow/apps.py", line 101, in ready
from .signals import dispatch
File "/data/app/code/itsm/workflow/signals/dispatch.py", line 27, in <module>
from itsm.workflow.signals import handlers
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 674, in exec_module
File "<frozen importlib._bootstrap_external>", line 779, in get_code
File "<frozen importlib._bootstrap_external>", line 487, in _compile_bytecode
EOFError: marshal data too short

有大佬遇到么？
@zanyzhao @breezelxp @hanshuaikang @luofann @CodeJamz

**Comment by hanshuaikang** [comment]
前端打包了吗，相关的环境变量是否已经配置完毕。
![image](https://user-images.githubusercontent.com/33194175/195016304-1418f3bf-62cc-4f8a-b54d-dc8e23749d98.png)

**Comment by qifeng998130** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TencentBlueKing/bk-itsm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月11日(星期二) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TencentBlueKing/bk-itsm] itsm二次开发问题 (Issue #975)





 
前端打包了吗，相关的环境变量是否已经配置完毕。

**Comment by qifeng998130** [comment]
![image](https://user-images.githubusercontent.com/12607253/195020984-18e10bec-71a2-4db6-928b-242d9e062499.png)

**Comment by hanshuaikang** [comment]
django的日志呢，报什么错

**Comment by qifeng998130** [comment]
Tue Oct 11 15:21:16 2022 - unable to load app 0 (mountpoint='') (callable not found or import error)
Tue Oct 11 15:21:16 2022 - mounting wsgi.py on /t/itsmnew
Traceback (most recent call last):
&nbsp; File "wsgi.py", line 16, in <module&gt;
&nbsp; &nbsp; application = get_wsgi_application()
&nbsp; File "/cache/.bk/env/lib/python3.6/site-packages/blueapps/core/wsgi.py", line 29, in get_wsgi_application
&nbsp; &nbsp; django.setup(set_prefix=False)
&nbsp; File "/cache/.bk/env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
&nbsp; &nbsp; apps.populate(settings.INSTALLED_APPS)
&nbsp; File "/cache/.bk/env/lib/python3.6/site-packages/django/apps/registry.py", line 83, in populate
&nbsp; &nbsp; raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Tue Oct 11 15:21:16 2022 - VACUUM: pidfile2 removed.





我搜索一下，感觉像版本问题。django和celery版本

**Comment by hanshuaikang** [comment]
同样的代码本地能运行起来么

**Comment by qifeng998130** [comment]
没有本地启动

**Comment by hanshuaikang** [comment]
建议先在本地开发环境尝试运行一次，一般直接fork仓库部署是行不通的
