### ISSUE TITLE
部署源码itsm

### ISSUE THREAD

**Issue by qifeng998130** [TencentBlueKing/bk-itsm#980]
产品：开源部署itsm
版本： bkce_basic_suite-6.0.5
环境信息： centos 7

[2022-10-20 10:57:01,960: INFO/MainProcess] Connected to amqp://itsmnew:**@rabbitmq.service.consul:5672/test_itsmnew
[2022-10-20 10:57:01,985: INFO/MainProcess] mingle: searching for neighbors
You are using Python 3.6. This version does not support timestamps with nanosecond precision and the OpenTelemetry SDK will use millisecond precision instead. Please refer to PEP 564 for more i
nformation. Please upgrade to Python 3.7 or newer to use nanosecond precision.
发现非2.6.0 之前的升级版本，已跳过修复
init redis settings
You are using Python 3.6. This version does not support timestamps with nanosecond precision and the OpenTelemetry SDK will use millisecond precision instead. Please refer to PEP 564 for more i
nformation. Please upgrade to Python 3.7 or newer to use nanosecond precision.
autodiscover rpc: rpc.components
autodiscover trigger: action.components
init api public key
init api public success
celery beat v4.4.5 (cliffs) is starting.
发现非2.6.0 之前的升级版本，已跳过修复
init redis settings
autodiscover rpc: rpc.components
autodiscover trigger: action.components
init api public key
init api public success
Traceback (most recent call last):
File "/data/app/code/manage.py", line 43, in <module>
execute_from_command_line(sys.argv)
File "/cache/.bk/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
utility.execute()
File "/cache/.bk/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
django.setup()
File "/cache/.bk/env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "/cache/.bk/env/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
app_config.import_models()
File "/cache/.bk/env/lib/python3.6/site-packages/django/apps/config.py", line 301, in import_models
self.models_module = import_module(models_module_name)
File "/cache/.bk/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load

File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/cache/.bk/env/lib/python3.6/site-packages/django_celery_beat/models.py", line 4, in <module>
import timezone_field
File "/cache/.bk/env/lib/python3.6/site-packages/timezone_field/__init__.py", line 1, in <module>
from timezone_field.fields import TimeZoneField
File "/cache/.bk/env/lib/python3.6/site-packages/timezone_field/fields.py", line 11, in <module>
class TimeZoneField(models.Field):
File "/cache/.bk/env/lib/python3.6/site-packages/timezone_field/fields.py", line 39, in TimeZoneField
default_tzs = [pytz.timezone(tz) for tz in pytz.common_timezones]
File "/cache/.bk/env/lib/python3.6/site-packages/timezone_field/fields.py", line 39, in <listcomp>
default_tzs = [pytz.timezone(tz) for tz in pytz.common_timezones]
File "/cache/.bk/env/lib/python3.6/site-packages/pytz/__init__.py", line 177, in timezone
_tzinfo_cache[zone] = build_tzinfo(zone, fp)
File "/cache/.bk/env/lib/python3.6/site-packages/pytz/tzfile.py", line 29, in build_tzinfo
typecnt, charcnt) = unpack(head_fmt, fp.read(head_size))
OSError: [Errno 12] Cannot allocate memory

@hanshuaikang

**Comment by hanshuaikang** [comment]
这个看起来是机器内存不够了

**Comment by qifeng998130** [comment]
内存够的
